name:                shredder
version:             0.1.0.0
github:              "fosu/shredder"
license:             BSD3
author:              "Rose"
maintainer:          "rose@lain.org.uk"
copyright:           "2018 Rose"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fosu/shredder#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams
- diagrams-core
- diagrams-lib
- diagrams-svg
- text
- scotty

library:
  source-dirs: src

executables:
  shredder:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shredder
